### ISSUE TITLE
[bug]: Guest checkout, France region validation failed

### ISSUE THREAD

**Issue by syno-jde** [magento/pwa-studio#3057]
**Describe the bug**

As guest, there is an error about address region (with country = France) when customer wants to proceed to shipping step.

**To reproduce**

1. Go to the checkout as guest with a valid cart
1. Set the address country with 'France'
1. Set the region with 'Ain' (the first one)
1. Fill all the required fields as usual
1. Click on "Continue to Shipping Method" button
1. Error "Invalid value of "1" provided for the regionId field." is displayed

**Expected behavior**

The address should be valid.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/46482676/110954529-e4890100-8348-11eb-9aa1-e5ae2e39b56a.PNG)

**Possible solutions**

France region code are mostly numeric, I think that's the issue. See \Magento\Customer\Model\Address\AbstractAddress::getRegionCode

**Please complete the following device information:**
 - Magento 2.4.2
 - PWA Studio 9.0.1

**Acceptance Criteria**
1. Root cause analysis is performed and actual underlying issue is fixed. In other words, we know that France doesn't work but do other countries have the same problem?
1. Users can successfully submit addresses in France (and all countries affected by this bug)

**Comment by fooman** [comment]
We ran into this as well. I am not 100% sure this can be solved in PWA Studio alone. France seems the only country where the region is mapped to numeric values (Ain => 01).

I believe the issue is around here:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/Address/AbstractAddress.php#L374
Which somehow GraphQl runs into while Magento with Luma does not.

The fix I applied was to change the database directly:
01 => FR-01

**Comment by sirugh** [comment]
This seems like a special case with the data. I'd prefer not to include special case fixes in the UI, especially since we would have to revert once fixed in the back end.

@cpartica can you confirm this is an issue with Magento Core or at least GQL?

**Comment by sirugh** [comment]
In the meantime I will open an internal bug and we can get it into triage hopefully.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by SergioDonati** [comment]
The component BillingAddress (packages/venia-ui/lib/components/CheckoutPage/BillingAddress/billingAddress.js) still have this specific issue. For reproduce just use checkmo as payment method.
